### ISSUE TITLE
无法正常安装部署，安装gradle过程中报错

### ISSUE THREAD

**Issue by sensorcloud** [WeBankFinTech/DeFiBus#21]
安装部署过程中到如下步骤时出现报错：

-----------------------------
deploy DeFiBusNamesrv

```
tar -zxvf DeFiBus_1.0.0.tar.gz
cd bin
sh runnamesrv.sh
```

-----------------------------------------

deploy DeFiBusBroker

```
tar -zxvf DeFiBus_1.0.0.tar.gz
cd bin
sh runbroker.sh
```
------------------------------------------
![微信图片_20200907174740](https://user-images.githubusercontent.com/7054088/92374458-50887380-f132-11ea-92e7-69338129d954.png)

**Comment by sensorcloud** [comment]
请求社区团队帮助指点一下，另外Defibus代码怎么这么少呢？不到2M的样子。。

**Comment by iNanos** [comment]
你好，Defibus包 应该是15M+， https://github.com/WeBankFinTech/DeFiBus/releases ，用这个包试试看
