### ISSUE TITLE
【出错】编译解压运行shell文件，报错生成错误日志。

### ISSUE THREAD

**Issue by sensorcloud** [WeBankFinTech/DeFiBus#23]
![微信图片_20200908093232](https://user-images.githubusercontent.com/7054088/92424916-40b37280-f1b8-11ea-85e6-06d503ba9bec.png)

### **如图所示，在部署过程中，编译解压运行shell文件时，报错生成了如上错误日志。**

**Comment by lrhkobe** [comment]
please adjust your jvm param in runbroker.sh, default config is: JAVA_OPT="${JAVA_OPT} -server -Xms8g -Xmx8g -Xmn4g"
