### ISSUE TITLE
【出错】DeFiBus_1.0.1.tar.gz   代码解压后运行出现shell文件错误

### ISSUE THREAD

**Issue by sensorcloud** [WeBankFinTech/DeFiBus#24]
https://github.com/WeBankFinTech/DeFiBus/releases 
DeFiBus_1.0.1.tar.gz
### 报错截图如下：

![111111111](https://user-images.githubusercontent.com/7054088/92425161-fda5cf00-f1b8-11ea-8658-5efecdd99261.png)

**Comment by iNanos** [comment]
这个应该是 DOS FORMAT 格式问题，我们处理下， 临时方式可以用 dos2unix 转一下

**Comment by sensorcloud** [comment]
用dos2unix转过之后依然如此
