### ISSUE TITLE
subscribe nearby may cause instance overload

### ISSUE THREAD

**Issue by qqeasonchen** [WeBankFinTech/DeFiBus#7]
As described in docs, message queue will be allocated to instances in same IDC even if there is only one consumer.  When some unexpected accident happen and there is only one consumer alive, it will bear the load of whole IDC, which may cause this consumer overload.

The feature of "auto expand or shrink queue number" will keep queue number equals to the number of alive consumer,  which enable us to know alive consumer number by evaluating queue number.  If there is only one alive consumer,  break the "nearby" rule and send message to not only message queue would be better to avoid overload.

**Comment by wqliang** [comment]
I'd like to pull a request to resolve this problem.

**Comment by qqeasonchen** [comment]
@wqliang nice
